version: "3"

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab_runner
    restart: always
    volumes:
      - "./config:/etc/gitlab-runner" # Configuration folder for the runner
      - "/var/run/docker.sock:/var/run/docker.sock" # For Docker-in-Docker
