include:
  - local: python.gitlab-ci.yml

stages:
  - build
  - deploy

build:
  extends: .local_runner
  stage: build
  script:
    - echo "CoolApp v1.0.0" > version.info
  artifacts:
    paths:
      - version.info

deploy:
  extends: .local_runner
  stage: deploy
  script:
    - cat ./version.info
