stages:
  - test

services:
  - mongo:latest
variables:
  MONGO_DB: test_db
  MONGO_HOST: mongo
  MONGO_PORT: 27017

test:
  stage: test
  image: python:3.9-alpine
  before_script:
    - pip install -r db_app/requirements.txt
  script:
    - cd db_app && python -m unittest discover

  tags:
    - ct-docker-linux
